### ISSUE TITLE
MacOS releases available from Solidity 0.6.9

### ISSUE THREAD

**Issue by xaviarias** [web3j/solidity-darwin-binaries#1]
The Solidity [releases page](https://github.com/ethereum/solidity/releases?after=v0.6.10) now contains MacOS artefacts.

There are a few versions missing in this repository to cover all 0.6.x versions:

- [0.6.3](https://github.com/ethereum/solidity/releases/tag/v0.6.3)
- [0.6.4](https://github.com/ethereum/solidity/releases/tag/v0.6.4)
- [0.6.5](https://github.com/ethereum/solidity/releases/tag/v0.6.5)
- [0.6.6](https://github.com/ethereum/solidity/releases/tag/v0.6.6)
- [0.6.7](https://github.com/ethereum/solidity/releases/tag/v0.6.7)
- [0.6.8](https://github.com/ethereum/solidity/releases/tag/v0.6.8)

**Comment by josh-richardson** [comment]
I've just released this: https://github.com/josh-richardson/svm-js

Which uses the Solidity releases page as a source of truth now, and in future will pull older macOS binaries from this page.

**Comment by xaviarias** [comment]
> I've just released this: https://github.com/josh-richardson/svm-js
> 
> Which uses the Solidity releases page as a source of truth now, and in future will pull older macOS binaries from this page.

I believe svm used a web endpoint pointing to the binaries?

**Comment by josh-richardson** [comment]
I believe this is the one: https://internal.services.web3labs.com/api/solidity/versions/

**Comment by xaviarias** [comment]
> I believe this is the one: https://internal.services.web3labs.com/api/solidity/versions/

Thanks Josh. So I guess with the new svm-js there's no need for that enpoint?
